# Generated by Django 4.2.1 on 2023-06-13 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomer', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Bron',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('haumany', models.CharField(max_length=15)),
                ('dait', models.CharField(max_length=33)),
                ('stolObject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='food.stol')),
            ],
        ),
    ]
