# Generated by Django 4.2.1 on 2023-05-20 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_menu_prase'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='prase',
            new_name='c',
        ),
    ]
