# Generated by Django 4.2.1 on 2023-06-14 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_stol_bron'),
    ]

    operations = [
        migrations.AddField(
            model_name='stol',
            name='man',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
