# Generated by Django 4.2.1 on 2023-05-20 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_rename_prase_menu_c'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='c',
            new_name='prace',
        ),
    ]
