# Generated by Django 4.2.1 on 2023-05-23 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_rename_c_menu_prace'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='description',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='image',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='prace',
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('prise', models.CharField(max_length=55)),
                ('image', models.ImageField(upload_to='image/')),
                ('menuObject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.menu')),
            ],
        ),
    ]
