# Generated by Django 4.2.1 on 2023-05-27 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0009_sliderproduct_aboutfoot'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutfoot',
            name='gram',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aboutfoot',
            name='sostav',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
