# Generated by Django 4.2.1 on 2023-05-28 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0011_alter_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='facebook',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='setting',
            name='instagram',
            field=models.URLField(blank=True, null=True),
        ),
    ]
