# Generated by Django 4.2.1 on 2023-05-28 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0012_setting_facebook_setting_instagram'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='schedule',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
