# Generated by Django 4.2.1 on 2023-05-28 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0014_product_melting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='melting',
            field=models.BooleanField(default=False),
        ),
    ]
